import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function ProductDetailsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {children}
      <h2>Features products</h2>
    </>
  );
}
